### ISSUE TITLE
Syncho à faire 

### ISSUE THREAD

**Issue by dzc34** [sebastianbergmann/phpunit-documentation-french#11]
_Commits on Feb 13, 2018_ 
- [x] [744ed7f Declare test method args from @depends](https://github.com/sebastianbergmann/phpunit-documentation-english/commit/744ed7f)  ---> code ---> simple / PR #12
- [x] [8dd236b Mention @depends shallowclone](https://github.com/sebastianbergmann/phpunit-documentation-english/commit/8dd236b) ---> traduction  ----> #13 
- [x] [29e117e Inline markup is no possible](https://github.com/sebastianbergmann/phpunit-documentation-english/commit/29e117e)  ----> typo ---> simple / PR #12
- [x] [8e703a0 Missing admonition](https://github.com/sebastianbergmann/phpunit-documentation-english/commit/8e703a0) ----> mise en forme  / PR #12
- [x] [e43d2f0 fix minor issues in Writing Tests for PHPUnit](https://github.com/sebastianbergmann/phpunit-documentation-english/commit/e43d2f0) ---> code ---> simple  / PR #12
- [x] [4255e94 replace assertEquals() in examples with assertSame()](https://github.com/sebastianbergmann/phpunit-documentation-english/commit/4255e94) ---> code  / PR #12
- [X] [52bb5e2 Fix assertArraySubset args default value](https://github.com/sebastianbergmann/phpunit-documentation-english/commit/52bb5e2) PR #9 
- [X] [84027c8 Issue #5 : document --configuration option with directory](https://github.com/sebastianbergmann/phpunit-documentation-english/commit/84027c8)  PR #8
- [X] [41eb981 Make consistent WRT "--dont-report-useless-tests"](https://github.com/sebastianbergmann/phpunit-documentation-english/commit/41eb981) PR #6
- [X] [a03ca05 Make consistent WRT "--dont-report-useless-tests"](https://github.com/sebastianbergmann/phpunit-documentation-english/commit/a03ca05) PR #6
- [x] [fc46957 Fix composer require version](https://github.com/sebastianbergmann/phpunit-documentation-english/commit/fc46957e62d0a9b652a707eb01f67a8e35854c16) ---> simple / PR #12
- [x] [bdc7a48 remove obsolete section from index](https://github.com/sebastianbergmann/phpunit-documentation-english/commit/bdc7a48)
- [x] [af00e26 separate quote from code block](https://github.com/sebastianbergmann/phpunit-documentation-english/commit/af00e26)
- [x] [6de4864 Bump copyright year](https://github.com/sebastianbergmann/phpunit-documentation-english/commit/6de4864)
- [x] [147b1ad make index.rst the entry point for the documentation](https://github.com/sebastianbergmann/phpunit-documentation-english/commit/147b1ad)
- [x] [ c11e6ea Migrate from DocBook XML to ReStructuredText](https://github.com/sebastianbergmann/phpunit-documentation-english/commit/c11e6ea)  ----> FORK commit
