### ISSUE TITLE
Synchros à faire

### ISSUE THREAD

**Issue by dzc34** [sebastianbergmann/phpunit-documentation-french#16]
commit(s) du 6 avril 2018 au **10 avril** 2018  :
- [x] [e1d3ec26 - add a more elaborate description of @testWith](https://github.com/sebastianbergmann/phpunit-documentation-english/commit/e1d3ec261ddd9870a39b8b729b0a655f9b25956f)  -> PR #28 
- [x] [bc72d5a0 -  add links to translations and documentation on creating a new translation](https://github.com/sebastianbergmann/phpunit-documentation-english/commit/bc72d5a0f5c94e4f2d60328cf73fd9fd998af91f)  -> PR #27 
- [x] [7965af23 - add CONTRIBUTING and use CODE_OF_CONDUCT from PHPUnit repo.](https://github.com/sebastianbergmann/phpunit-documentation-english/commit/7965af23def4a84341cf61bc30fe905c44e98fc6)  ---> PR #26 
- [x] [b87fc979 - add requirements.txt for managing python dependencies](https://github.com/sebastianbergmann/phpunit-documentation-english/commit/b87fc979e7b91be8f385c6ac09612957f8840b34) ---> PR #25

commit(s) du 18 février 2018 au **29 mars** 2018  :
- [x] [09891331 - Precision about mocking static methods](https://github.com/sebastianbergmann/phpunit-documentation-english/pull/30)   ----> PR #24
- [x] [ca9e5b907 - fix #4 by adding the missing sample code blocks](https://github.com/sebastianbergmann/phpunit-documentation-english/commit/ca9e5b907bca1b1b4e89ce32aa982f7261644280) -----> #22
- [x] [645e58dd - Remove the deprecated PHPUnit_Extensions_TestDecorator part](https://github.com/sebastianbergmann/phpunit-documentation-english/commit/645e58ddddc4ef4e7b6df72ae4e81454289ec572) ----> PR #20
- [x] [7903992 - Remove content that does not fit into a manual](https://github.com/sebastianbergmann/phpunit-documentation-english/commit/7903992eeabd6018c69c69f74c74d301ee9a0d30) ----> refactor ----> PR #19
- [x] [1cbe671 - Cleanup](https://github.com/sebastianbergmann/phpunit-documentation-english/commit/1cbe6711b4dbd382f418067b2b4408ee864a723e) ----> code  ----> PR #18
- [x] [ 90f051c - Fix](https://github.com/sebastianbergmann/phpunit-documentation-english/commit/90f051c7f8fb0bbaed74a596749681a0ac06546e)  ----> code / simple ---> PR #18 
- [x] [ 38d351a -  Fix occurences of PHPUnit_* namespaces](https://github.com/sebastianbergmann/phpunit-documentation-english/commit/38d351a257e13a05a40bc6c2a1bc96465629d69d) ---> code ---> PR #17 
----
synchro précédente  #11 

----

template:
`- [ ] []()`
