### ISSUE TITLE
Synchro à faire : commits du 5 juin au 7 novembre 2018

### ISSUE THREAD

**Issue by dzc34** [sebastianbergmann/phpunit-documentation-french#63]
Si possible traiter les commits les plus anciens ( = commencer par le bas du message), 
en particulier ceux marqués "**help wanted**" qui sont bloquant.

Quasiment tous les commits (sauf mention contraire) doivent être fait dans la branche 7.0 et mergé ensuite dans les branches 7.1, 7.2, 7.3, 7.4 et master.

* commits du **25 octobre**   au **7 novembre** 2018 ----> OK
* commits du **6 aout**  au **25 octobre** 2018 ----> OK
* commits du **5 juin**  au **6 aout** 2018 ----> OK
* commits avant le 5 juin à traiter  **help wanted** 

### commits du **25 octobre**   au **7 novembre** 2018
- [x] branche **7.0** --> 7.1, 7.2, 7.3 and 7.4  --> merged
  - [x] 27 - [01885 - Initial work on proofreading automation](https://github.com/sebastianbergmann/phpunit-documentation-english/commit/01885d8b388aaa6303e8e6fd648394f15f782e09)  ---> PR #67 --> merged
- [x] branche **7.4** --> master  --> merged
  - [x] 26 - [75632a - Use finally to simplify example code](https://github.com/sebastianbergmann/phpunit-documentation-english/commit/75632a4be498acd0720c29f0f7b1323a4ce17ab9) (uniquement sur 7.4 et master)   ---> PR #69  --> merged

### commits du **6 aout**  au **25 octobre** 2018
![Visuel des commit du 6 aout au 25 octobre 2018 ](https://user-images.githubusercontent.com/6709977/48318605-87a79f80-e603-11e8-90d8-34d71ac4afed.png)
- [x] branche **7.3** --> 7.4   --> merged
  - [x] 24 - [fb8a0e - Fix: Add cacheResult to default phpunit.xml](https://github.com/sebastianbergmann/phpunit-documentation-english/commit/fb8a0ee6477552104c99fafdfe548c96b4948ecd) à partir de 7.3  ---> PR #68 --> merged
- [x] branche **7.0** --> 7.1, 7.2, 7.3 and 7.4  --> merged
  - [x] 25 - [b3de9fa - Removed mapTestClassNameToCoveredClassName](https://github.com/sebastianbergmann/phpunit-documentation-english/commit/b3de9fab4fc49be908100a9485ba39eaf7a88ff4)  ---> PR #65 --> merged
  - [x] 23 - [82919 - Mention the "force" parameter for <env>](https://github.com/sebastianbergmann/phpunit-documentation-english/commit/8291953a9f1ba93fe7215d13c4895a1f4620736f) ---> PR #65  --> merged
  - [x] 22 - [09318d - Adding reference link to installation of DbUnit](https://github.com/sebastianbergmann/phpunit-documentation-english/commit/09318dde0ff81ab25f43b7ff939957939bbf1c6a)  ---> PR #65 --> merged
  - [x] 21 - [660dc - issue-92 fixed documentation about doubles](https://github.com/sebastianbergmann/phpunit-documentation-english/commit/660dc5c6538a0cb44d42356e96b0cdfc59dfd7bc)  ---> PR #65 --> merged
  - [x] 20 - [076c1a - Document escaped % in assertStringNotMatchesFormat](https://github.com/sebastianbergmann/phpunit-documentation-english/commit/076c1a686ae594d2374de0608e4345118b5f772e)  ---> PR #67 --> merged
  - [x] 19 - [d8ce7d8 - Add link with Russian translation to CONTRIBUTING.md](https://github.com/sebastianbergmann/phpunit-documentation-english/commit/d8ce7d8f9890935a972f35b5adceac12b406d713) ---> PR #64 --> merged
  - [x] 18 - [44f0fc5 - Add to Russian documentation link](https://github.com/sebastianbergmann/phpunit-documentation-english/commit/44f0fc52292c26ee10970fd53e9bb93ee9e4b945)  ---> PR #64 --> merged
  - [x] 17 - [f06509f - writing-tests-for-phpunit: make syntax highlighting methods](https://github.com/sebastianbergmann/phpunit-documentation-english/commit/f06509fe277586f96dbe98091484611f6e97a6a8)  ---> PR #65 --> merged
  - [x] 16 - [4ff19db9 - extending-phpunit: fixes](https://github.com/sebastianbergmann/phpunit-documentation-english/commit/4ff19db9547ef68b9cc82e7b8ea377b5df7a8f69) --> PR #66 --> merged
  - [x] 15 - [d410b - installation: highlight syntax of command](https://github.com/sebastianbergmann/phpunit-documentation-english/commit/d410ba284d24e7826351a6dd23d74d738290ce35)  ---> PR #65 --> merged
  - [x] 14 - [2f806b - Fixed typo](https://github.com/sebastianbergmann/phpunit-documentation-english/commit/2f806b03123a2dbcd25ec96a1a5f3a7cec8fdd97) ---> typo anglais ---> rien à faire

### commits du **5 juin**  au **6 aout** 2018
![Visuel des commit du 5 juin au 6 aout 2018 ](https://user-images.githubusercontent.com/6709977/48318421-064f0d80-e601-11e8-9d05-19f224ebda3b.png)
- [x] branche **7.0** --> 7.1, 7.2, 7.3 and 7.4  --> merged
  - [x] 13 - [ed51a7 - Elaborate](https://github.com/sebastianbergmann/phpunit-documentation-english/commit/ed51a7c1ddd8cc40a7b3f56ef48754df8f42102d)
  - [x] 12 - database: use https for links    ---> PR #65 --> merged
    -  [x] [484dc84 - database: use https for links](https://github.com/sebastianbergmann/phpunit-documentation-english/commit/484dc849ccad4efb0b44169faa9046b184f79776)  ---> PR #65 --> merged
    -  [x] [ba008a - database: use https for links](https://github.com/sebastianbergmann/phpunit-documentation-english/commit/ba008aeed7773b140f34b5119aaebbafa70eb24e)  ---> PR #65 --> merged
  - [x] 11 - [57c19c - Fix name of XML configuration file attribute](https://github.com/sebastianbergmann/phpunit-documentation-english/commit/57c19c22d2a4b2df9bb6dd61ba11f0c6d24c948a)   ---> PR #65 --> merged
  - [x] 10 - [4f7b270a - Fallback to @Small was removed in PHPUnit 4.7](https://github.com/sebastianbergmann/phpunit-documentation-english/commit/4f7b270adccbd5fd7624c88d49a8e68f0693e85d)    ---> PR #65 --> merged
  - [x] 9 - [e74ae4 - Fix copyright syntax type](https://github.com/sebastianbergmann/phpunit-documentation-english/commit/e74ae4371403c52f50d73a241c9457a6b08e92d0)  ---> PR #64 --> merged
  - [x] 8 - [7ff88cb - extending-phpunit: fix code style](https://github.com/sebastianbergmann/phpunit-documentation-english/commit/7ff88cb39efce57acbd7a9d6e1b8d2fe41b0f491)  --> PR #66 --> merged
  - [x] 7 - [2e6b03 - ShortTestListener - add missing interface implementation](https://github.com/sebastianbergmann/phpunit-documentation-english/commit/2e6b036bec54be50148fd97baded0526a4bed6f0) --> PR #66 --> merged
  - [x] 6 - [544cae5 - SimpleTestListener - add missing addWarning method](https://github.com/sebastianbergmann/phpunit-documentation-english/commit/544cae52793bae63e9db740b8312c330995f70b9) --> PR #66 --> merged
  - [x] 5 - [ea57a20 - Update assertions.rst](https://github.com/sebastianbergmann/phpunit-documentation-english/commit/ea57a208ebbd177f849aadceadda2eead185658e)  ---> PR #65 --> merged
  - [x] 4 - [231e038c - Improve database.rst](https://github.com/sebastianbergmann/phpunit-documentation-english/commit/231e038c4324dbeb475c0d86e2af06f37318316c)  ---> PR #64 --> merged
  - [x] 3 - [252113 - Adds required typhinting to extending listener section](https://github.com/sebastianbergmann/phpunit-documentation-english/commit/2521134b6d8381c2cb9d65fafa23cb394d16f8a2)  --> PR #66 --> merged
  - [x] 2 - [224c21 -  Sincerest apologies - :void is what should have been in the example ](https://github.com/sebastianbergmann/phpunit-documentation-english/commit/224c21ae4b81299e5ea04e697fc3f61b05712930) --> PR #66 --> merged
  - [x] 1 - [0e56bfd - Remove BaseTestListener documentation ](https://github.com/sebastianbergmann/phpunit-documentation-english/commit/0e56bfd0a3c8f1cbfeb05e5fa5f3dd55900c0432) --> PR #66 --> merged

### commits avant le **5 juin** à traiter
- [ ] branche **7.1** --> 7.2, 7.3 and 7.4
  - [ ] [b7615d26 - Simplify meaning of constraint in their table ](https://github.com/sebastianbergmann/phpunit-documentation-english/commit/b7615d2674f4fad4372280f588c2865278bf77af) 
 ----> à priori "typo en anglais" / rien à faire   ----> à, vérifier  ---> **help wanted** 

----
synchro précédente  #31

----

template:
`- [ ] []()`

**Comment by gbprod** [comment]
Hello! Désolé j'étais un peu absent ces derniers temps, je reprends du service !
Je peux me baser sur cette PR et prendre ceux ou tu as besoin d'aide en priorité !

**Comment by dzc34** [comment]
moi aussi, j'avais levé le pied. C'est les PR de @l-vo qui m'ont motivés à résoudre les conflits de fusion qui traînaient.

Plusieurs modifications concernent le fichier `extending-phpunit.rst` 
et sont à priori à faire dans l'ordre : 1, 2, 3, 6, 7, 8 et 16
 si t'es motivé : https://github.com/sebastianbergmann/phpunit-documentation-english/commits/7.0/src/extending-phpunit.rst

Sinon, comment tu traduirais :
 _"Please target the oldest branch affected in case your pull request fixes a bug or typo."_  
ajouté dans le fichier CONTRIBUTING.md

**Comment by l-vo** [comment]
Merci pour vos actions :)

**Comment by gbprod** [comment]
thx @dzc34
